[package]
name = "peace"
version = "1.0.0"
authors = ["Melody Horn <melody@boringcactus.com>"]
edition = "2018"

[features]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]

[dependencies]
amethyst = "0.13.2"
